### PR TITLE
switch to github actions

### LINKED ISSUE #37: migrate travis to github actions

### PR DESCRIPTION
**Pull request by marwahaha**
fixes #37

### CODE REVIEW

**Comment by jbroz11** [comment]
Have you looked into using this https://github.com/julia-actions/julia-runtest

**Comment by marwahaha** [comment]
todo: add this to actions
```
    - julia --color=yes -e 'import Pkg; import IonSim; cd(joinpath(dirname(pathof(IonSim)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
 ```

**Comment by marwahaha** [comment]
let's get the tests working, then we'll do codecov

**Comment by marwahaha** [comment]
oh, wow, tests passed

**Review by jbroz11 — APPROVED** [review]

**Pull request merged**
