### PR TITLE
add comments to hamiltonian test

### PR DESCRIPTION
**Pull request by marwahaha**
I tried to add some comments and fix the test. But nothing I tried seemed to work.

What I noticed:
1. The norms of qoH and H are always the same, but the difference has usually a large norm. 
2. Both objects are Hermitian.
3. There's a weird sqrt(3) floating around in one of the modes; why?
4. I tried playing with the `timescale` but didn't notice it improving the issue.
5. I think the ion's level is labeled wrong ("D5/2", -1/2) -> ("D5/2", -5/2) but it didn't seem to improve the issue
6. Sometimes delta, phi, Omega are negative; is that ok?
7. I relabeled the ions for clarity.

Maybe something more fundamental is broken.

### CODE REVIEW

**Comment by neil-glikin** [comment]
Yeah I guess it must be the phases. If it happened from split-species then it must be from the electronic part. So it might be easy to check by trying with a super simple 2-level Hamiltonian with no motional degrees so freedom, so that there is essentially only one (off-diagonal) matrix element to compare between the IonSim construction and the manual construction. I unfortunately won't be able to work on it the rest of this week though :(

**Comment by marwahaha** [comment]
I tried playing around some more but I'm not sure how to generate the Hamiltonian you mention Neil.

**Comment by neil-glikin** [comment]
I found the problem; it was with the test. The way that the laser wavelength was defined needed to be changed from how it had been defined pre-split-species, but I hadn't done that properly. This resulted in the parameter $\Delta$ not actually reflecting the real detuning, and hence a disagreement in phases in the manually- and IonSim-constructed Hamiltonians.

For some reason I was only able to get this fix to work on the master branch, so I pushed that as well. To fix-h-test, I've pushed what I would think would be the same thing, but for some reason the test fails. I like @marwahaha's added comments and changes for readability so it would be nice to still incorporate them, but something functional must have changed as well that I haven't figured out.

**Comment by marwahaha** [comment]
@neil-glikin is there a way to make IonSim error with that kind of input? It feels like we should prevent people from making this particular mistake. 

I've updated this PR, it's ready to go after a review from either of you.

**Review by jbroz11 — APPROVED** [review]
Looks good to me

**Comment by marwahaha** [comment]
ok, that makes sense; sublevel transitions are different than level transitions.
It worries me because if even we can make the mistake, users will very likely make it.

**Comment by marwahaha** [comment]
ok, that makes sense; sublevel transitions are different than level transitions.
I think if even we can make the mistake, users will very likely make it.

**Pull request merged**
