### PR TITLE
[DO NOT MERGE] Switch to unitful

### PR DESCRIPTION
**Pull request by marwahaha**
This PR is not finished

### CODE REVIEW

**Comment by neil-glikin** [comment]
Error may lie with the tests in test_dynamics.jl

**Comment by neil-glikin** [comment]
Was able to get this working for some simple cases including the MS code example snippet on the front page. Only exception was that the units of time in the hamiltonian (including the function defining the time-dependent Rabi frequency and the array of time values passed into the solver) seemed to need to be simple numbers. Is it expected to be possible to make these unitful as well yet? (Am I missing something or is it just not done yet?)

**Comment by marwahaha** [comment]
I havent made everything forced to be unitful yet. Also, the dynamics code
seems to run fastest without units, so I havent fit that in yet. Let me see
what I can do

**Comment by neil-glikin** [comment]
Maybe we can make it so that the user passes in units (which then also removes the need to use the `timescale` argument), and then the solver strips away the units on the backend to maintain the speed

**Comment by marwahaha** [comment]
Closing as won't do (for now)

**Pull request closed without merging**
