### PR TITLE
Multiple species in same ionchain

### PR DESCRIPTION
**Pull request by marwahaha**
Please double check my work.

I rederived from the reference linked, and it looks like if $\ell = \ell_1$, then the first $u_m$ term is offset by a factor of $M_m/M_1$.

It seems to work, but I have some questions:
1. I dont know of any known examples. Can we verify this against known data?
2. When the mass differences are too much, the ions are no longer in order. But then this is very wrong; and the equations would be wrong too. Perhaps we can call an error in this case?

### CODE REVIEW

**Comment by neil-glikin** [comment]
To clarify, I think (without looking at it more yet) your work is probably valid assuming that the mass of the first ion defines the strength of the trapping potential: $V(x) = \tfrac12m_1\nu^2x^2$ where $\nu$ is the parameter given as one of the `com_frequencies`. The open question as I see it right now is one of how we parametrize things from the user's perspective; should they parameterize it in terms of the first ion, or in terms of the actual lowest-frequency in-phase mode of the chain?

Here's another source I just found:
https://link.springer.com/content/pdf/10.1007/s100530170275.pdf

**Comment by jbroz11** [comment]
@marwahaha  actually have an almost fully working version of this on a local branch atm. Was waiting on finishing an example before posting. Sorry, didn't realize anyone else was working on it.

I did have the same thing for the equilibrium positions. 

@neil-glikin The frequencies are a feature of the pseudo potential. The fact that they correspond to com frequencies when all masses are equal is a secondary point. IMO we should continue to quantify them the same way and then update the terminology or maybe clarify in relevant doc strings.

**Comment by neil-glikin** [comment]
To clarify, my point isn't about when modes do and don't correspond to true center-of-mass motion. The frequencies aren't just a feature of the pseudo-potential; they also depend on the mass. A single ion in a given pseudo-potential will have a different frequency depending on its mass. This means that there is an ambiguity in the meaning of `com_frequencies` given heterogeneous chains (irrespective of whether or not they correspond to true center-of-mass motion). We need to specify the pseudo-potential, but a frequency alone isn't enough.

**Comment by jbroz11** [comment]
I see what you're saying now. Also, I didn't include this effect in my work so far.. I guess we can discuss a convention today at the meeting (like maximum mass or maybe the mass of the first ion in the chain). Shouldn't matter too much as long as we clarify in the docs.

**Comment by jbroz11** [comment]
And it seems like [here](https://doi.org/10.1103/PhysRevA.103.012610) at least, they just specify by the actual com motion of the mixed chain. That probably makes the most sense.

**Comment by jbroz11** [comment]
Closing this based on Neil's observation.

**Pull request closed without merging**
